### ISSUE TITLE
pyspharm on new mac M2 processor?

### ISSUE THREAD

**Issue by VolkmarWirth** [conda-forge/pyspharm-feedstock#24]
### Comment:

Hi there,

I have been using pyspharm for may years. Recently I got a new macbook computer which has the new M2 chip. Unfortunately I was not able to get pyspharm installed (using conda). Conda simply does not find "pyspharm". On the other hand, I know that pyspharm exists on conda-forge, right?

Does anyone know whether there is an issue with the new M2 chip architecture? It used to be very simple to install pyspharm on my older macbook with the old intel chip. 

Any help would be appreciated. 

Many thanks in advance,
Volkmar

**Comment by ocefpaf** [comment]
Done in #33

**Comment by VolkmarWirth** [comment]
Thank you so much, this is very helpful for me! My legacy code now work on my new macbook, and you saved me plenty of time.
