### ISSUE TITLE
Update for latest master?

### ISSUE THREAD

**Issue by ajdawson** [conda-forge/pyspharm-feedstock#9]
Since pyspharm does not have any releases on Github this feedstock uses a specific commit. I'd like to know what the procedure should be for updating this feedstock? There is a new commit on the pyspharm master branch that makes fixes required for compatibility with recent versions of numpy and I would like the conda-forge package to include this.

Should the commit and build number be updated whilst leaving the version at 1.09 as was done previously? Ping @ocefpaf

**Comment by ocefpaf** [comment]
> Should the commit and build number be updated whilst leaving the version at 1.09 as was done previously? Ping @ocefpaf

Unless they changed the version number somewhere yep. That is pretty much what I would do.

**Comment by ocefpaf** [comment]
Done in #30
